# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc7d86d356318292f732987af3cfc06d6ca3c1d75d7bcf3e11d56b6fd147daaec59a984d7a4829d63c59ea888ad8db7a227419a68b129717a0d61a8c2dfeb0df

test:
  secret_key_base: e44fe425d5a465ccd8e43084434ba1d9fd31ee26d5bba4f8b536cb6859f53793e19540f6dac8ac8e9e35409881339d65509c7dc8c51101d9b140ccbb939ed8fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
